[package]
name = "spawn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#jemallocator = { version = "0.5" }

[workspace]

[profile.release]
debug = "line-tables-only"
